---
name: Pull Request Build, Tag, & Push
on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  pre-build:
    uses: ./.github/workflows/reusable_pre-build.yml
    secrets: inherit
  build-develop-open:
    needs: pre-build
    if: github.base_ref == 'develop' && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}-develop'
      tags: pr-${{ github.event.number }}
    secrets: inherit
  build-develop-merge:
    needs: pre-build
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}-develop'
      tags: pr-${{ github.event.number }},latest
    secrets: inherit
  build-main-open:
    needs: pre-build
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }}
    secrets: inherit
  build-main-merge:
    needs: pre-build
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == true
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@main
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }},latest-rc
    secrets: inherit
  trivy-scans:
    needs: pre-build
    if: (github.base_ref == 'develop' || github.base_ref == 'main' || github.base_ref == 'master' ) && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_trivy-scans.yml@main
    secrets: inherit